package cn.codexin.wechatofficial.model;

public class AccessToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token.id
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token.app_id
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token.access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token.gmt_token_expire
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    private Long gmtTokenExpire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token.id
     *
     * @return the value of access_token.id
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token.id
     *
     * @param id the value for access_token.id
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token.app_id
     *
     * @return the value of access_token.app_id
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token.app_id
     *
     * @param appId the value for access_token.app_id
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token.access_token
     *
     * @return the value of access_token.access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token.access_token
     *
     * @param accessToken the value for access_token.access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token.gmt_token_expire
     *
     * @return the value of access_token.gmt_token_expire
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public Long getGmtTokenExpire() {
        return gmtTokenExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_token.gmt_token_expire
     *
     * @param gmtTokenExpire the value for access_token.gmt_token_expire
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    public void setGmtTokenExpire(Long gmtTokenExpire) {
        this.gmtTokenExpire = gmtTokenExpire;
    }
}