package cn.codexin.wechatofficial.mapper;

import cn.codexin.wechatofficial.model.AccessToken;
import cn.codexin.wechatofficial.model.AccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    long countByExample(AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int deleteByExample(AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int insert(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int insertSelective(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    List<AccessToken> selectByExampleWithRowbounds(AccessTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    List<AccessToken> selectByExample(AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    AccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccessToken record, @Param("example") AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int updateByExample(@Param("record") AccessToken record, @Param("example") AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int updateByPrimaryKeySelective(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbg.generated Wed Apr 22 22:48:41 CST 2020
     */
    int updateByPrimaryKey(AccessToken record);
}